import PrusaSlicer from './prusaslicer';

export default class SlicerFacotry {
    static getSlicer(gcode) {
        if (!gcode) return null;
        if (gcode.startsWith('; generated by PrusaSlicer')) {
            return new PrusaSlicer();
        }
        return null;
    }
}