import PrusaSlicer from './prusaslicer';
import Cura from './cura'
import SuperSlicer from './superslicer';
import ideaMaker from './ideaMaker';

export default class SlicerFacotry {
    static getSlicer(gcode) {
        if (!gcode) return null;
        let header = gcode.substring(0,10000);
        if (header.includes('; generated by PrusaSlicer')) {
            return new PrusaSlicer();
        }
        else if (header.includes(';Generated with Cura_SteamEngine')) {
            return new Cura();
        }
        else if (header.includes('; generated by SuperSlicer')) {
            return new SuperSlicer();
        }
        else if (header.includes('Sliced by ideaMaker')){
            return new ideaMaker();
        }
        
        return null;
    }
}